============================= test session starts =============================
platform win32 -- Python 3.8.1, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: C:\Users\ADMIN\projects\strategy
plugins: cov-2.12.1
collected 8 items / 1 error / 7 selected

=================================== ERRORS ====================================
________ ERROR collecting auxloss/tests/test_aux_power_consumption.py _________
ImportError while importing test module 'C:\Users\ADMIN\projects\strategy\auxloss\tests\test_aux_power_consumption.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\appdata\local\programs\python\python38\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
auxloss\tests\test_aux_power_consumption.py:7: in <module>
    import mock
E   ModuleNotFoundError: No module named 'mock'

----------- coverage: platform win32, python 3.8.1-final-0 -----------
Name                                          Stmts   Miss  Cover
-----------------------------------------------------------------
auxloss\aux_power_consumption.py                 28     28     0%
auxloss\auxsystem.py                             27     24    11%
auxloss\tests\test_aux_power_consumption.py      54     48    11%
auxloss\tests\test_auxsystem.py                  31     19    39%
-----------------------------------------------------------------
TOTAL                                           140    119    15%

=========================== short test summary info ===========================
ERROR auxloss/tests/test_aux_power_consumption.py
!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
============================== 1 error in 0.35s ===============================
